name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]  # Removed 22.x as it's still in beta

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Added caching for faster builds

    - name: Install Dependencies
      run: npm ci  # Using ci instead of install for cleaner installs

    - name: Install Gulp CLI
      run: npm install --global gulp-cli

    - name: Build
      run: gulp build  # Specifically calling gulp build instead of just gulp

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'  # Only deploy on main branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Replace with your build output directory
